version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
